"use client";
import Link from 'next/link';
import { useState } from 'react';
import { useEnterprise } from './WorkspaceProvider';
import { Badge, buttonClass, fieldClass, PageIntro, Panel } from './ui';
import { ehrs } from '@/lib/enterprise/validation';
import type { Facility, Department } from '@/types/enterprise';

export function LiveWorkspace({view}:{view:string}) {
  const {data,error,mutate,refresh}=useEnterprise();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Facility|Department|null>(null),[query,setQuery]=useState('');
  async function save(event:React.FormEvent<HTMLFormElement>,action:string,extra:Record<string,unknown>={}){event.preventDefault();const form=event.currentTarget;const fields=Object.fromEntries(new FormData(form));setBusy(true);setMessage('');try{await mutate(action,{...fields,...extra});setMessage('Saved successfully.');setEditing(null);if(action!=='settings')form.reset();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
  if(error)return <Panel><p role="alert">{error}</p><button className={`${buttonClass} mt-4`} onClick={()=>void refresh()}>Retry</button></Panel>;
  if(!data)return <Panel>Loading organization…</Panel>;
  const org=data.organization;const title=view==='dashboard'?'Your organization at a glance':view==='organizations'?'Organization':view==='users'?'Enterprise Administrators':view[0].toUpperCase()+view.slice(1);
  return <><PageIntro title={title} description={org.name}/>{message&&<p role="status" className="mb-5 text-sm">{message}</p>}
    {(view==='dashboard'||view==='analytics')&&<><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[['Facilities',data.facilities.length],['Departments',data.departments.length],['Enterprise Admins',data.admins.length],['Active Clinicians',0],['Notes Generated',0],['Estimated Time Saved','0 minutes'],['Monthly Usage',0],['AI Utilization','0%']].map(([label,value])=><Panel key={label}><p className="text-sm text-[var(--muted-foreground)]">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p></Panel>)}</div><Panel className="mt-5"><h2 className="font-semibold">Clinical activity</h2><p className="mt-3 text-sm text-[var(--muted-foreground)]">No Enterprise clinical activity is available yet. These zero states will populate when clinical workflows are connected.</p></Panel>{view==='dashboard'&&<div className="mt-5 grid gap-4 sm:grid-cols-3">{['organizations','facilities','departments','users','analytics','integrations','billing','support','settings'].map(path=><Link key={path} href={`/enterprise/${path}`} className="rounded-xl border border-[var(--border)] bg-[var(--card)] p-4 text-sm capitalize">{path==='organizations'?'Organization':path} →</Link>)}</div>}</>}
    {view==='organizations'&&<Panel><h2 className="text-xl font-semibold">{org.name}</h2><div className="my-4"><Badge>{org.status}</Badge></div><p>{[org.country,org.state].filter(Boolean).join(' · ')}</p><p className="mt-4 text-sm">{data.facilities.length} facilities · {data.departments.length} departments</p></Panel>}
    {(view==='facilities'||view==='departments')&&<><div className="grid gap-5 md:grid-cols-2">{(view==='facilities'?data.facilities:data.departments).map(row=><Panel key={row.id}><h2 className="font-semibold">{row.name}</h2><p className="mt-2 text-sm text-[var(--muted-foreground)]">{'location' in row?row.location:data.facilities.find(f=>f.id===row.facility_id)?.name}</p><button className="mt-4 text-sm text-[var(--primary)]" onClick={()=>setEditing(row)}>Edit</button></Panel>)}</div><Panel className="mt-5"><h2 className="font-semibold">{editing?'Edit':'Add'} {view==='facilities'?'facility':'department'}</h2><form key={editing?.id||'new'} className="mt-5 space-y-4" onSubmit={e=>void save(e,view==='facilities'?'facility':'department',editing?{id:editing.id}:{})}><label className="block text-sm">Name<input required name="name" defaultValue={editing?.name} className={fieldClass}/></label>{view==='facilities'?<><label className="block text-sm">Type<input name="kind" defaultValue={editing&&'kind' in editing?editing.kind:'Other'} className={fieldClass}/></label><label className="block text-sm">Location<input name="location" defaultValue={editing&&'location' in editing?editing.location||'':''} className={fieldClass}/></label></>:<label className="block text-sm">Facility<select required name="facility_id" defaultValue={editing&&'facility_id' in editing?editing.facility_id:''} className={fieldClass}><option value="">Choose facility</option>{data.facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}<button disabled={busy} className={buttonClass}>{busy?'Saving…':'Save'}</button>{editing&&<button type="button" className="ml-4" onClick={()=>setEditing(null)}>Cancel</button>}</form></Panel></>}
    {view==='users'&&<Panel><label className="text-sm">Search administrators<input className={fieldClass} type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="mt-5 space-y-4">{data.admins.filter(a=>a.full_name.toLowerCase().includes(query.toLowerCase())).map(a=><div key={a.user_id} className="flex justify-between border-b border-[var(--border)] py-3"><p>{a.full_name}</p><Badge>Enterprise Admin</Badge></div>)}</div><p className="mt-5 text-xs text-[var(--muted-foreground)]">Clinicians do not authenticate through this portal.</p></Panel>}
    {view==='integrations'&&<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{ehrs.filter(e=>e!=='Other').map(ehr=><Panel key={ehr}><h2 className="font-semibold">{ehr}</h2><div className="mt-5"><Badge>{data.integrations.find(i=>i.ehr_type===ehr)?.connection_status||'Coming Soon'}</Badge></div></Panel>)}</div>}
    {view==='billing'&&<><Panel><h2 className="font-semibold">Enterprise contracts</h2><p className="mt-3 text-sm">Subscription status: {data.contracts.some(c=>c.status==='Signed'&&c.payment_status==='Received'&&c.start_date<=new Date().toISOString().slice(0,10)&&c.end_date>=new Date().toISOString().slice(0,10))?'Active':org.subscription_status}</p><p className="mt-2 text-xs text-[var(--muted-foreground)]">Enterprise contracts and payment confirmations are managed by KOKO LABS. Contact support for billing changes.</p></Panel>{data.contracts.length===0?<Panel className="mt-5">No Enterprise contracts recorded yet.</Panel>:data.contracts.map(c=><Panel key={c.id} className="mt-5"><h3 className="font-semibold">{c.status} contract</h3><p className="mt-3 text-sm">{c.start_date} – {c.end_date}</p><p className="mt-2 text-sm">{(c.amount_cents/100).toLocaleString('en-US',{style:'currency',currency:c.currency})} · Payment: {c.payment_status}</p></Panel>)}</>}
    {view==='settings'&&<Panel><form className="space-y-5" onSubmit={e=>void save(e,'settings',{include_time_saved:new FormData(e.currentTarget).get('include_time_saved')==='on'})}>{[['name','Organization name',org.name],['country','Country',org.country||''],['state','State',org.state||''],['timezone','Time zone',org.timezone]].map(([name,label,value])=><label key={name} className="block text-sm">{label}<input name={name} required={name!=='state'} defaultValue={value} className={fieldClass}/></label>)}<label className="block text-sm">Reporting period<select name="reporting_period" defaultValue={org.reporting_period} className={fieldClass}>{['Weekly','Monthly','Quarterly'].map(p=><option key={p}>{p}</option>)}</select></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="include_time_saved" defaultChecked={org.include_time_saved}/>Include estimated time saved</label><button disabled={busy} className={buttonClass}>Save settings</button></form></Panel>}
    {view==='support'&&<><Panel><h2 className="font-semibold">Contact KOKO LABS Support</h2><form className="mt-5 space-y-4" onSubmit={e=>void save(e,'ticket')}><label className="block text-sm">Subject<input required name="subject" className={fieldClass} maxLength={200}/></label><label className="block text-sm">Message<textarea required name="message" rows={4} maxLength={4000} className={fieldClass} placeholder="Do not include patient information."/></label><button disabled={busy} className={buttonClass}>Submit support request</button></form></Panel><div className="mt-5 space-y-4">{data.tickets.map(t=><Panel key={t.id}><h3 className="font-semibold">{t.subject}</h3><p className="my-3 text-sm whitespace-pre-wrap">{t.message}</p><Badge>{t.status}</Badge></Panel>)}</div></>}
  </>;
}
