"use client";
import { useEffect, useState } from 'react';
import { portalRequest } from './PortalAuth';
import { buttonClass, fieldClass, Panel } from './ui';
import type { Organization } from '@/types/enterprise';
type SetupFacility={name:string;kind:string;location:string;departments:string[]};
export function SetupWizard({token}:{token:string}) {
  const [invitation,setInvitation]=useState<{organization:Organization;email:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[step,setStep]=useState(0);
  const [name,setName]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
  const [facilities,setFacilities]=useState<SetupFacility[]>([{name:'',kind:'Other',location:'',departments:[]}]);
  useEffect(()=>{let active=true;portalRequest<{organization:Organization;email:string}>('enterprise','setup/validate',{token}).then(value=>{if(active)setInvitation(value);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[token]);
  const titles=['Verify setup link','Create Enterprise Admin account','Set password','Review organization','Add facilities','Add departments','Finish setup'];
  async function next(event:React.FormEvent) {
    event.preventDefault();setError('');
    if(step===2&&(password.length<12||password!==confirm)){setError('Use at least 12 characters and matching passwords.');return;}
    if(step<6){setStep(step+1);return;}
    setBusy(true);try{await portalRequest('enterprise','setup/finish',{token,name,password,facilities:facilities.map(f=>({...f,departments:f.departments.map(d=>d.trim()).filter(Boolean)}))});window.location.assign('/enterprise/dashboard');}catch(e){setError(e instanceof Error?e.message:'Unable to complete setup.');setBusy(false);}
  }
  return <div className="mx-auto max-w-3xl px-5 py-12"><p className="text-xs font-semibold uppercase tracking-widest text-[var(--primary)]">ShiftNote Enterprise Setup</p><h1 className="mt-3 text-3xl font-semibold">{titles[step]}</h1><p className="my-5 text-sm text-[var(--muted-foreground)]">Step {step+1} of {titles.length}</p><div className="mb-6 h-2 rounded-full bg-[var(--muted)]"><div className="h-full rounded-full bg-[var(--primary)]" style={{width:`${(step+1)/7*100}%`}}/></div>{error&&<p role="alert" className="mb-5 text-sm">{error}</p>}{!invitation?<Panel>{error?'Request a new setup link from KOKO LABS.':'Checking your secure setup link…'}</Panel>:<Panel><form onSubmit={next} className="space-y-5">
    {step===0&&<><h2 className="font-semibold">Your organization is approved</h2><p>{invitation.organization.name}</p><p className="text-sm">This invitation is for {invitation.email}.</p></>}
    {step===1&&<><label className="block text-sm">Full name<input required value={name} onChange={e=>setName(e.target.value)} className={fieldClass} autoComplete="name" maxLength={200}/></label><p className="text-sm">Administrator email: {invitation.email}</p><p className="text-xs text-[var(--muted-foreground)]">Your account and organization are activated together when you finish setup. If you already use this email with ShiftNote, use your existing password in the next step.</p></>}
    {step===2&&<><label className="block text-sm">Password<input required minLength={12} maxLength={128} type="password" value={password} onChange={e=>setPassword(e.target.value)} className={fieldClass} autoComplete="new-password"/></label><label className="block text-sm">Confirm password<input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className={fieldClass} autoComplete="new-password"/></label></>}
    {step===3&&<><h2 className="font-semibold">{invitation.organization.name}</h2><p className="text-sm">{[invitation.organization.country,invitation.organization.state].filter(Boolean).join(' · ')}</p><p className="text-sm text-[var(--muted-foreground)]">Confirm this is your organization. Contact KOKO LABS if these details are incorrect.</p></>}
    {step===4&&<>{facilities.map((facility,i)=><fieldset key={i} className="rounded-xl border border-[var(--border)] p-4"><legend className="px-2 text-sm">Facility {i+1}</legend>{(['name','kind','location'] as const).map(key=><label key={key} className="mb-3 block text-sm capitalize">{key}<input required={key==='name'} className={fieldClass} value={facility[key]} onChange={e=>setFacilities(facilities.map((f,index)=>index===i?{...f,[key]:e.target.value}:f))}/></label>)}{facilities.length>1&&<button type="button" className="text-sm" onClick={()=>setFacilities(facilities.filter((_,index)=>index!==i))}>Remove facility</button>}</fieldset>)}<button type="button" className="text-sm font-semibold text-[var(--primary)]" disabled={facilities.length>=50} onClick={()=>setFacilities([...facilities,{name:'',kind:'Other',location:'',departments:[]}])}>+ Add facility</button></>}
    {step===5&&<>{facilities.map((facility,i)=><label key={i} className="block text-sm">Departments for {facility.name}<input className={fieldClass} placeholder="Nursing, Rehabilitation, Care Coordination" value={facility.departments.join(',')} onChange={e=>setFacilities(facilities.map((f,index)=>index===i?{...f,departments:e.target.value.split(',')}:f))}/><span className="text-xs text-[var(--muted-foreground)]">Separate names with commas. You can add departments later.</span></label>)}</>}
    {step===6&&<><h2 className="font-semibold">Ready to activate {invitation.organization.name}</h2><p className="text-sm">{name} · {invitation.email}</p><p className="text-sm">{facilities.length} facilities will be created.</p><p className="text-sm text-[var(--muted-foreground)]">Finishing activates your administrator access and permanently invalidates this setup link.</p></>}
    <div className="flex justify-between pt-4">{step>0?<button disabled={busy} type="button" onClick={()=>setStep(step-1)}>Back</button>:<span/>}<button disabled={busy} className={buttonClass}>{busy?'Completing setup…':step===6?'Finish Setup':'Continue'}</button></div>
  </form></Panel>}</div>;
}
