/* eslint-disable react/jsx-key */
import { PolicyPage } from "@/components/public/PolicyPage";
export default function PrivacyPage(){return <PolicyPage title="Privacy Policy" intro="This Privacy Policy explains how ShiftNote collects, uses, shares, and protects information when you use our website and clinical documentation copilot." sections={[
["Information we collect",<><p>We collect account details such as your name, email address, authentication identifiers, profession, workplace category, experience range, EHR preference, and documentation preferences. We also process information you submit to generate documentation, including typed content, attachments, and voice recordings.</p><p>We collect limited technical and usage data needed to secure, operate, diagnose, and improve the service, such as device, browser, log, and feature-interaction data.</p></>],
["How we use information",<p>We use information to authenticate users, personalize workflows, generate requested drafts, maintain history and favorites, provide support, process subscriptions, prevent abuse, and improve reliability. We do not use clinical content for advertising.</p>],
["Clinical and sensitive information",<p>ShiftNote is a documentation-assistance tool, not an electronic health record. Only enter information you are authorized to process. Your organization remains responsible for its legal, privacy, security, retention, and patient-notice obligations. Do not assume use of the service alone establishes HIPAA compliance or a business associate relationship.</p>],
["Service providers and disclosures",<p>We may share the minimum necessary information with service providers that support authentication, cloud hosting, AI processing, payment processing, monitoring, and customer support. We may also disclose information when required by law, to protect users or the service, or in connection with a corporate transaction. We do not sell personal information.</p>],
["Retention and security",<p>We retain information for as long as needed to provide the service, meet contractual and legal obligations, resolve disputes, and protect the service. We use administrative, technical, and organizational safeguards, but no online system can guarantee absolute security.</p>],
["Your choices and rights",<p>You may update account information and request access, correction, deletion, or export by contacting support. Rights vary by location and may be subject to verification and legal exceptions. You can control cookies and permissions through your browser, though disabling required features may limit the service.</p>],
["Children, international use, and changes",<p>ShiftNote is not directed to children under 18. Information may be processed in countries where our providers operate. We may update this policy and will post the effective date; material changes may receive additional notice.</p>],
["Contact",<p>Questions or privacy requests can be sent to <a className="underline" href="mailto:support@shiftnote.care">support@shiftnote.care</a>.</p>],
]}/>} 
