/* eslint-disable react/jsx-key */
import { PolicyPage } from "@/components/public/PolicyPage";
export default function TermsPage(){return <PolicyPage title="Terms of Service" intro="These Terms govern access to and use of ShiftNote. By creating an account or using the service, you agree to them." sections={[
["Eligibility and accounts",<p>You must be at least 18 and legally able to enter this agreement. Provide accurate account information, protect your credentials, and notify us of suspected unauthorized access. You are responsible for activity under your account.</p>],
["Clinical use and professional responsibility",<><p>ShiftNote provides AI-assisted documentation drafts. It does not provide medical advice, diagnosis, treatment, or emergency services and does not replace professional judgment. AI output can be incomplete or inaccurate.</p><p>You must independently review, edit, validate, and attest every output before use. You remain responsible for clinical decisions, documentation, coding, legal compliance, and obtaining authorization to submit information.</p></>],
["Acceptable use",<p>Do not use ShiftNote unlawfully; attempt unauthorized access; disrupt or reverse engineer the service; upload malicious material; infringe rights; misrepresent AI output as independently verified; or submit information you lack authority to process.</p>],
["Subscriptions and billing",<p>Paid plans renew for their stated billing period until canceled. Prices and taxes are shown before purchase. Billing is processed by our payment provider. Except where law requires otherwise, fees already paid are nonrefundable. Cancel before renewal to avoid the next charge; access continues through the paid period.</p>],
["Ownership and feedback",<p>ShiftNote and its software, branding, and content are owned by us or our licensors. You retain rights in content you submit. You grant us the limited rights needed to process it and provide the service. Feedback may be used without restriction or compensation.</p>],
["Availability and changes",<p>We may modify, suspend, or discontinue features and may impose reasonable limits to maintain security and reliability. We do not promise uninterrupted or error-free operation.</p>],
["Disclaimers and limitation of liability",<p>To the fullest extent permitted by law, the service is provided “as is” and “as available,” without implied warranties. ShiftNote is not liable for indirect, incidental, special, consequential, or punitive damages, lost profits or data, or clinical decisions based on output. Any aggregate liability is limited to amounts paid for the service in the six months before the event giving rise to the claim.</p>],
["Termination",<p>You may stop using the service at any time. We may suspend or terminate access for violations, security risk, nonpayment, or legal requirements. Provisions that by nature should survive will remain effective.</p>],
["Governing terms and contact",<p>Applicable law and venue will be determined by the contracting ShiftNote entity and mandatory consumer laws. If a provision is unenforceable, the rest remains effective. Questions can be sent to <a className="underline" href="mailto:support@shiftnote.app">support@shiftnote.app</a>.</p>],
]}/>} 
