import Link from "next/link";
import { ArrowUpRight, BarChart3, Building2, Check, FileText, Layers, Network, ShieldCheck, Sparkles, Users } from "lucide-react";
import { MarketingChrome } from "@/components/enterprise/MarketingChrome";
import { Badge, DemoLink, Panel } from "@/components/enterprise/ui";
import { ehrPlatforms } from "@/lib/enterprise/demo-data";

export default function EnterprisePage() {
  return <MarketingChrome>
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[1.1fr_1fr] lg:px-8 lg:py-24">
      <div><Badge>Built for the way your teams work</Badge><h1 className="mt-6 text-5xl font-semibold leading-[1.05] tracking-[-.045em] md:text-6xl">ShiftNote<br /><span className="text-[var(--primary)]">Enterprise</span></h1><p className="mt-6 max-w-xl text-xl leading-8">AI Documentation built for Healthcare Organizations.</p><p className="mt-4 max-w-xl text-sm leading-7 text-[var(--muted-foreground)]">Bring your people, facilities, and documentation workflows into one shared view. More clarity for your organization. More time for your clinicians.</p><div className="mt-8 flex flex-wrap items-center gap-5"><DemoLink /><Link href="/enterprise/demo" className="inline-flex items-center gap-2 text-sm font-semibold">Explore the workspace <ArrowUpRight className="size-4" /></Link></div><p className="mt-5 text-xs text-[var(--muted-foreground)]">Explore our Enterprise vision. This preview uses sample data.</p></div>
      <div className="rounded-[28px] border border-[var(--border)] bg-[var(--primary-soft)] p-5 md:p-7"><Panel><div className="flex items-center justify-between gap-4"><span className="flex items-center gap-2 text-sm font-semibold"><Building2 className="size-5 text-[var(--primary)]" />Your organization, connected</span><Badge>Preview</Badge></div><div className="mt-7 grid grid-cols-3 gap-3">{[["4", "Facilities"], ["12", "Departments"], ["248", "Clinicians"]].map(([value,label]) => <div key={label} className="rounded-xl bg-[var(--background)] px-3 py-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-[var(--muted-foreground)]">{label}</p></div>)}</div><p className="mb-4 mt-7 text-xs font-medium text-[var(--muted-foreground)]">One foundation. Across every care setting.</p>{["Organization oversight", "Facility coordination", "Clinical documentation"].map((label,index) => <div key={label} className="mt-3 flex items-center gap-3 rounded-xl border border-[var(--border)] px-3 py-4 text-sm"><span className="grid size-7 place-items-center rounded-lg bg-[var(--primary-soft)] text-xs font-semibold text-[var(--primary)]">0{index+1}</span>{label}<Check className="ml-auto size-4 text-[var(--primary)]" /></div>)}</Panel></div>
    </section>
    <section id="overview" className="border-y border-[var(--border)] bg-[var(--card)]"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--primary)]">Enterprise Overview</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight">A common foundation for every team.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[var(--muted-foreground)]">Designed to connect organization leaders with the workflows their teams rely on. Review the workspace today and help shape what comes next.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{[[Building2, "Organizations", "See facilities and teams within a clear organizational structure."], [Network, "Departments", "Explore a shared framework for coordinating care teams."], [FileText, "Documentation", "Bring the vision of professional AI documentation to your organization."]].map(([Icon,title,description]) => { const FeatureIcon = Icon as typeof Building2; return <Panel key={String(title)}><FeatureIcon className="size-6 text-[var(--primary)]" /><h3 className="mt-4 font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{String(description)}</p></Panel>; })}</div></div></section>
    <section id="features" className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--primary)]">Features & Benefits</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Less fragmentation. A clearer view.</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[Layers,"Multi-Facility Management","Organize your care network in one workspace."],[Users,"Team Visibility","Understand how clinicians and departments fit together."],[BarChart3,"Enterprise Analytics","Preview usage and estimated time-saving insights."],[Sparkles,"AI Documentation","Explore documentation support built around professional roles."]].map(([Icon,title,description]) => { const FeatureIcon = Icon as typeof Layers; return <Panel key={String(title)}><FeatureIcon className="size-5 text-[var(--primary)]" /><h3 className="mt-5 font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted-foreground)]">{String(description)}</p></Panel>; })}</div></section>
    <section id="organizations" className="mx-auto grid max-w-7xl gap-8 px-5 pb-16 md:grid-cols-2 lg:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[var(--primary)]">Healthcare Organizations</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Built around your care setting.</h2><p className="mt-4 text-sm leading-7 text-[var(--muted-foreground)]">From a single facility to a growing network, shape an Enterprise experience around the people delivering care.</p></div><div className="grid gap-3 sm:grid-cols-2">{["Hospitals & Health Systems", "Skilled Nursing Facilities", "Rehabilitation Centers", "Home Health Organizations", "Outpatient Clinics", "Long-Term Care Networks"].map(item => <div key={item} className="flex items-center gap-3 rounded-xl border border-[var(--border)] bg-[var(--card)] p-4 text-sm"><Building2 className="size-4 shrink-0 text-[var(--primary)]" />{item}</div>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-5 pb-16 md:grid-cols-2 lg:px-8"><Panel><ShieldCheck className="size-7 text-[var(--primary)]" /><h2 className="mt-4 text-xl font-semibold">Enterprise Security</h2><p className="mt-3 text-sm leading-7 text-[var(--muted-foreground)]">Planned foundations include organization roles, access controls, and audit logs. These capabilities are not enabled in this public prototype. Do not enter patient information.</p><Badge>Planned capabilities</Badge></Panel><Panel><BarChart3 className="size-7 text-[var(--primary)]" /><h2 className="mt-4 text-xl font-semibold">Enterprise Analytics</h2><p className="mt-3 text-sm leading-7 text-[var(--muted-foreground)]">Explore a sample view of active clinicians, documentation volume, and AI utilization across your care network.</p><Link href="/enterprise/analytics" className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-[var(--primary)]">Preview analytics <ArrowUpRight className="size-4" /></Link></Panel></section>
    <section className="border-y border-[var(--border)] bg-[var(--card)]"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><Badge /><h2 className="mt-4 text-3xl font-semibold tracking-tight">EHR Integrations</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[var(--muted-foreground)]">Future versions will support secure EHR integration through industry-standard technologies. No systems are connected in this preview.</p><div className="mt-7 flex flex-wrap gap-3">{ehrPlatforms.map(ehr => <span key={ehr} className="rounded-xl border border-[var(--border)] px-4 py-3 text-sm font-medium">{ehr}</span>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="rounded-[28px] bg-[var(--primary)] p-8 text-white md:p-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-white/75">Request Enterprise Demo</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-tight">Let’s shape the next chapter of documentation.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/80">Explore how ShiftNote Enterprise could fit your organization.</p><DemoLink className="mt-7 border border-white/40" /></div></section>
  </MarketingChrome>;
}
