"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Apple, Globe2 as Chrome, Sparkles } from "lucide-react";
import { useAuth, friendlyAuthError } from "./AuthProvider";
import { StatusMessage } from "@/components/ui/status-message";

const field = "h-12 w-full rounded-xl border border-[var(--border)] bg-[var(--card)] px-4 outline-none focus:border-[var(--primary)] focus:ring-2 focus:ring-[var(--primary)]/15";
export function AuthCard({ mode }: { mode: "login" | "signup" }) {
  const auth = useAuth(); const router = useRouter(); const params = useSearchParams();
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<{type:"error"|"success";text:string}|null>(null);
  const target = mode === "signup" ? "/onboarding" : (params.get("returnTo") || "/dashboard");
  async function run(action:()=>Promise<void>, destination=target) { setBusy(true); setMessage(null); try { await action(); router.push(destination); } catch(e){ setMessage({type:"error",text:friendlyAuthError(e)}); } finally { setBusy(false); } }
  async function submit(e:FormEvent){e.preventDefault(); if(mode==="signup" && password.length<8){setMessage({type:"error",text:"Use a password with at least 8 characters."});return;} await run(()=>mode==="signup"?auth.signUpEmail(name.trim(),email.trim(),password):auth.signInEmail(email.trim(),password));}
  async function reset(){if(!email.trim()){setMessage({type:"error",text:"Enter your email address first."});return;} setBusy(true);try{await auth.resetPassword(email.trim());setMessage({type:"success",text:"Password reset instructions were sent if an account exists for that email."});}catch(e){setMessage({type:"error",text:friendlyAuthError(e)});}finally{setBusy(false);}}
  return <div className="w-full max-w-md rounded-[28px] border border-[var(--border)] bg-[var(--card)] p-6 shadow-xl sm:p-8"><div className="mb-7"><span className="grid size-11 place-items-center rounded-xl bg-[var(--primary)] text-white"><Sparkles className="size-5" /></span><h1 className="mt-5 text-2xl font-semibold">{mode==="login"?"Welcome back":"Create your account"}</h1><p className="mt-2 text-sm text-[var(--muted-foreground)]">{mode==="login"?"Sign in to continue to your clinical copilot.":"Start simplifying your clinical documentation."}</p></div>{message&&<StatusMessage type={message.type} className="mb-5">{message.text}</StatusMessage>}<form className="space-y-4" onSubmit={submit}>{mode==="signup"&&<label className="block text-sm font-medium">Full name<input className={`${field} mt-1.5`} required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} /></label>}<label className="block text-sm font-medium">Email<input className={`${field} mt-1.5`} type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label className="block text-sm font-medium">Password<input className={`${field} mt-1.5`} type="password" minLength={mode==="signup"?8:1} required autoComplete={mode==="login"?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} /></label>{mode==="login"&&<button type="button" className="text-sm font-medium text-[var(--primary)]" onClick={reset}>Forgot password?</button>}<button disabled={busy} className="h-12 w-full rounded-xl bg-[var(--primary)] font-semibold text-white disabled:opacity-60">{busy?"Please wait…":mode==="login"?"Log in":"Create account"}</button></form><div className="my-5 flex items-center gap-3 text-xs text-[var(--muted-foreground)]"><span className="h-px flex-1 bg-[var(--border)]"/>or continue with<span className="h-px flex-1 bg-[var(--border)]"/></div><div className="grid gap-3 sm:grid-cols-2"><button disabled={busy} className="flex h-11 items-center justify-center gap-2 rounded-xl border border-[var(--border)]" onClick={()=>run(auth.signInGoogle,mode==="signup"?"/onboarding":target)}><Chrome className="size-4"/>Google</button><button disabled={busy} className="flex h-11 items-center justify-center gap-2 rounded-xl border border-[var(--border)]" onClick={()=>run(auth.signInApple,mode==="signup"?"/onboarding":target)}><Apple className="size-4"/>Apple</button></div><p className="mt-6 text-center text-sm text-[var(--muted-foreground)]">{mode==="login"?"New to ShiftNote? ":"Already have an account? "}<Link className="font-semibold text-[var(--primary)]" href={mode==="login"?"/signup":"/login"}>{mode==="login"?"Sign up":"Log in"}</Link></p><p className="mt-4 text-center text-xs text-[var(--muted-foreground)]">By continuing, you agree to our <Link className="underline" href="/terms">Terms</Link> and <Link className="underline" href="/privacy">Privacy Policy</Link>.</p></div>;
}
